### PR TITLE
Ronan

### PR DESCRIPTION
**Pull request by LostSamurai**
Hehe... gottem! Oh and imma accept my own pull request!

### CODE REVIEW

**Comment by LostSamurai** [comment]
ugh

**Comment by isaacaddis** [comment]
same

**Comment by LostSamurai** [comment]
im so sad. I can't resolve this conflict

**Comment by LostSamurai** [comment]
I've literally tried everything... I might just edit it using the software provided by the web...
I give up with this comand promt thig

**Pull request merged**
